import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
        uk: {
            enterMovie: "Введіть назву фільма",
            notFound: "Жодного фільму за введеною назвою не знайдено",
            main:"Головна",
            new:"Новинки",
            popular:"Популярні",
            input:"Введіть назву фільма",
            byAlfabet:"Алфавітом",
            byPopular:"Популярністю",
            byRate:"Рейтингом",
            dark:"Темна тема",
            light:"Світла тема",
            soon:"Скоро на екранах",
            best:"Найкращі фільми за рейтингом",
            result:"Результат пошуку",
            socialNetwork:"Ми в соціальаних мережах:",
            genre:"Жанр:",
            date:"Дата виходу -",
            rate:"Рейтинг -",
        },
        ru: {
            enterMovie: "Введите название фильма",
            notFound: "С указаным названием нет ни одного фильма",
            main:"Главная",
            new:"Новинки",
            popular:"Популярные",
            input:"Введите название фильма",
            byAlfabet:"Алфавитом",
            byPopular:"Популярностью",
            byRate:"Рейтингом",
            dark:"Тёмная тема",
            light:"Светлая тема",
            soon:"Скоро на экранах",
            best:"Лучшие фильмы  по рейтингу",
            result:"Результат поиска",
            socialNetwork:"Мы в cоциальных сетях:",
            genre:"Жанр:",
            date:"Дата выхода -",
            rate:"Рейтинг -",
        },
        en: {
            enterMovie: "Please enter a name of movie",
            notFound: "There aren't any movies for the title that you entered",
            main:"Main",
            new:"New movies",
            popular:"Popular movies",
            byPopular:"Popular",
            byRate:"Rate",
            input:"Please enter movie name",
            byAlfabet:"Alfabet",
            dark:"Dark theme",
            light:"Light theme",
            soon:"Coming soon",
            best:"The best movies",
            result:"Search results",
            socialNetwork:"We are in social networks:",
            genre:"Genre:",
            date:"Release date -",
            rate:"Rate -",
        },

    }
)